server:
  port: 8089
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rest_client?useSSL=false
    username: root
    password: admin123
    driver-class-name: com.mysql.jdbc.Driver
  rabbitmq:
    host: 192.168.80.128 #rabbitMQ的ip地址
    port: 5672 #端口
    username: itcast
    password: admin123
    virtual-host: /

logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: cn.itcast.hotel.pojo